/************************************************************************************************************************
*@Author: Masumi Vyas @Date: 06/08/2021
*
*@Teacher: A. Correiro
*
*@File Name: ArrayHighLowMasumi.java
*
*@Description: program that asks the user for the length of an array that will be populated with random numbers.
*****************************************************************************************************************/
import java.util.Random;
import java.util.Scanner;
public class ArrayHighLowMasumi {
   public static void main(String[] args) {
   
// -- Variable Declaration & Initialization / user input

      System.out.println("Enter the size of the array: ");
      Scanner uI = new Scanner(System.in); // creates scanner object called uI
      int size = uI.nextInt();
      
// -- Program Execution
      int array[] = new int [size]; // initializes array
      double[] val = new double[size];
      double min = Double.MAX_VALUE; // establishes variable so that the lowest number from the array can be indicated
      double max = Double.MIN_VALUE; // establishes variable so that the highest number from the array can be indicated
      System.out.println("The array is as follows..."); // indicates the beginning of array to user
      for (int i = 0; i < size; i++) {
         val[i] = new Random().nextInt(10000); // Indicates the max number that can be generated by the program (10000)
         System.out.println(val[i]);
      }
      for (int i = 0; i < val.length; i++) { // program runs for statement so conditions can be repeated for each array number
         if (val[i] < min)
            min = val[i];
         if (val[i] > max)
            max = val[i];
      }
      System.out.println("Minimum number = " + min); // outputs lowest number from array
      System.out.println("Maximum number = " + max); // outputs highest number from array
      
   }// close main
} // close ArrayHighLowMasumi.java